//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Px.SelfService.WebParts.PersonalSettings {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class PersonalSettings {
        
        protected global::System.Web.UI.WebControls.Literal ltr_SharedNav;
        
        protected global::System.Web.UI.WebControls.Literal ltr_Username;
        
        protected global::System.Web.UI.WebControls.RequiredFieldValidator dummyValidator;
        
        protected global::System.Web.UI.WebControls.TextBox dummyTextBox;
        
        protected global::System.Web.UI.WebControls.Literal ltr_Debug;
        
        protected global::System.Web.UI.WebControls.Label lbl_DisplayName;
        
        protected global::System.Web.UI.WebControls.Literal ltr_DisplayName;
        
        protected global::System.Web.UI.WebControls.LinkButton lnk_ChangeName;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl section_DisplayName;
        
        protected global::System.Web.UI.WebControls.Label lbl_ChangeName;
        
        protected global::System.Web.UI.WebControls.Label lbl_FirstName;
        
        protected global::System.Web.UI.WebControls.TextBox txb_FirstName;
        
        protected global::System.Web.UI.WebControls.RequiredFieldValidator require_FirstName;
        
        protected global::System.Web.UI.WebControls.Label lbl_LastName;
        
        protected global::System.Web.UI.WebControls.TextBox txb_LastName;
        
        protected global::System.Web.UI.WebControls.RequiredFieldValidator require_LastName;
        
        protected global::System.Web.UI.WebControls.Button btn_ChangeName;
        
        protected global::System.Web.UI.WebControls.Button btn_CancelChangeName;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl section_ChangeName;
        
        protected global::System.Web.UI.WebControls.Label lbl_Password;
        
        protected global::System.Web.UI.WebControls.LinkButton lnk_ChangePassword;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl section_DisplayPassword;
        
        protected global::System.Web.UI.WebControls.Label lbl_ChangePassword;
        
        protected global::System.Web.UI.WebControls.Label lbl_CurrentPassword;
        
        protected global::System.Web.UI.WebControls.TextBox txb_CurrentPassword;
        
        protected global::System.Web.UI.WebControls.RequiredFieldValidator require_CurrentPassword;
        
        protected global::System.Web.UI.WebControls.Label lbl_NewPassword;
        
        protected global::System.Web.UI.WebControls.TextBox txb_NewPassword;
        
        protected global::System.Web.UI.WebControls.RequiredFieldValidator require_NewPassword;
        
        protected global::System.Web.UI.WebControls.CustomValidator custom_Password;
        
        protected global::System.Web.UI.WebControls.Label lbl_ConfirmNewPassword;
        
        protected global::System.Web.UI.WebControls.TextBox txb_ConfirmNewPassword;
        
        protected global::System.Web.UI.WebControls.CompareValidator compare_ConfirmPassword;
        
        protected global::System.Web.UI.WebControls.Button btn_ChangePassword;
        
        protected global::System.Web.UI.WebControls.Button btn_CancelChangePassword;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl section_ChangePassword;
        
        protected global::System.Web.UI.WebControls.Label lbl_DisplayPhoneNumber;
        
        protected global::System.Web.UI.WebControls.Literal ltr_DisplayPhoneNumber;
        
        protected global::System.Web.UI.WebControls.LinkButton lnk_ChangePhoneNumber;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl section_DisplayPhoneNumber;
        
        protected global::System.Web.UI.WebControls.Label lbl_ChangePhoneNumber;
        
        protected global::System.Web.UI.WebControls.Label lbl_NewPhoneNumber;
        
        protected global::System.Web.UI.WebControls.TextBox txb_NewPhoneNumber;
        
        protected global::System.Web.UI.WebControls.RequiredFieldValidator require_PhoneNumber;
        
        protected global::System.Web.UI.WebControls.RegularExpressionValidator regex_PhoneNumber;
        
        protected global::System.Web.UI.WebControls.Button btn_ChangePhoneNumber;
        
        protected global::System.Web.UI.WebControls.Button btn_CancelChangePhoneNumber;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl section_ChangePhoneNumber;
        
        protected global::System.Web.UI.UpdatePanel UpdatePanelOne;
        
        public static implicit operator global::System.Web.UI.TemplateControl(PersonalSettings target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Literal @__BuildControlltr_SharedNav() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.ltr_SharedNav = @__ctrl;
            @__ctrl.ID = "ltr_SharedNav";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Literal @__BuildControlltr_Username() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.ltr_Username = @__ctrl;
            @__ctrl.ID = "ltr_Username";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControldummyValidator() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            this.dummyValidator = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "dummyValidator";
            @__ctrl.CssClass = "hidden";
            @__ctrl.ControlToValidate = "dummyTextBox";
            @__ctrl.ValidationGroup = "dummy";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControldummyTextBox() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.dummyTextBox = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "dummyTextBox";
            @__ctrl.CssClass = "hidden";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Literal @__BuildControlltr_Debug() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.ltr_Debug = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "ltr_Debug";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_DisplayName() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_DisplayName = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_DisplayName";
            @__ctrl.CssClass = "pxLabel";
            @__ctrl.Text = "Name";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Literal @__BuildControlltr_DisplayName() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.ltr_DisplayName = @__ctrl;
            @__ctrl.ID = "ltr_DisplayName";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllnk_ChangeName() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lnk_ChangeName = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lnk_ChangeName";
            @__ctrl.CausesValidation = false;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Change Name"));
            @__ctrl.Click -= new System.EventHandler(this.ShowChangeName);
            @__ctrl.Click += new System.EventHandler(this.ShowChangeName);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlsection_DisplayName() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.section_DisplayName = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "section_DisplayName";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "pxDisplaySetting");
            @__ctrl.Visible = true;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllbl_DisplayName();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        <div class=\"clear\"></div>\r\n                        "));
            global::System.Web.UI.WebControls.Literal @__ctrl2;
            @__ctrl2 = this.@__BuildControlltr_DisplayName();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl3;
            @__ctrl3 = this.@__BuildControllnk_ChangeName();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_ChangeName() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_ChangeName = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_ChangeName";
            @__ctrl.CssClass = "pxHeading";
            @__ctrl.Text = "Change Name";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_FirstName() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_FirstName = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_FirstName";
            @__ctrl.Text = "First Name";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxb_FirstName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txb_FirstName = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txb_FirstName";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(125D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlrequire_FirstName() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            this.require_FirstName = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "require_FirstName";
            @__ctrl.ValidationGroup = "ChangeName";
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            @__ctrl.CssClass = "pxErrorText";
            @__ctrl.ControlToValidate = "txb_FirstName";
            @__ctrl.ErrorMessage = "First Name is required.";
            @__ctrl.Enabled = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_LastName() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_LastName = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_LastName";
            @__ctrl.Text = "Last Name";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxb_LastName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txb_LastName = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txb_LastName";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(125D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlrequire_LastName() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            this.require_LastName = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "require_LastName";
            @__ctrl.ValidationGroup = "ChangeName";
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            @__ctrl.CssClass = "pxErrorText";
            @__ctrl.ControlToValidate = "txb_LastName";
            @__ctrl.ErrorMessage = "Last Name is required.";
            @__ctrl.Enabled = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtn_ChangeName() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btn_ChangeName = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btn_ChangeName";
            @__ctrl.ValidationGroup = "ChangeName";
            @__ctrl.CssClass = "pxBtn";
            @__ctrl.Text = "Change Name";
            @__ctrl.Click -= new System.EventHandler(this.ChangeName_Click);
            @__ctrl.Click += new System.EventHandler(this.ChangeName_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtn_CancelChangeName() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btn_CancelChangeName = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btn_CancelChangeName";
            @__ctrl.CssClass = "pxBtnCancel";
            @__ctrl.Text = "Cancel";
            @__ctrl.CausesValidation = false;
            @__ctrl.Click -= new System.EventHandler(this.HideChangeName);
            @__ctrl.Click += new System.EventHandler(this.HideChangeName);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlsection_ChangeName() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.section_ChangeName = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "section_ChangeName";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "pxChangeSetting");
            @__ctrl.Visible = false;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllbl_ChangeName();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        <div class=\"clear\"></div>\r\n                        <div" +
                        " class=\"pxFields\">\r\n                            "));
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControllbl_FirstName();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            @__ctrl3 = this.@__BuildControltxb_FirstName();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl4;
            @__ctrl4 = this.@__BuildControlrequire_FirstName();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("        \r\n                        </div>\r\n                        <div class=\"pxF" +
                        "ields\">\r\n                            "));
            global::System.Web.UI.WebControls.Label @__ctrl5;
            @__ctrl5 = this.@__BuildControllbl_LastName();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            @__ctrl6 = this.@__BuildControltxb_LastName();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl7;
            @__ctrl7 = this.@__BuildControlrequire_LastName();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("        \r\n                        </div>\r\n                        <div class=\"cle" +
                        "ar\"></div>\r\n                        <div class=\"pxButtons\">\r\n                   " +
                        "         "));
            global::System.Web.UI.WebControls.Button @__ctrl8;
            @__ctrl8 = this.@__BuildControlbtn_ChangeName();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
            global::System.Web.UI.WebControls.Button @__ctrl9;
            @__ctrl9 = this.@__BuildControlbtn_CancelChangeName();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </div>\r\n                    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_Password() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_Password = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_Password";
            @__ctrl.CssClass = "pxLabel";
            @__ctrl.Text = "Password";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllnk_ChangePassword() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lnk_ChangePassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lnk_ChangePassword";
            @__ctrl.CausesValidation = false;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Change Password"));
            @__ctrl.Click -= new System.EventHandler(this.ShowChangePassword);
            @__ctrl.Click += new System.EventHandler(this.ShowChangePassword);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlsection_DisplayPassword() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.section_DisplayPassword = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "section_DisplayPassword";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "pxDisplaySetting");
            @__ctrl.Visible = true;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllbl_Password();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl2;
            @__ctrl2 = this.@__BuildControllnk_ChangePassword();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_ChangePassword() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_ChangePassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_ChangePassword";
            @__ctrl.CssClass = "pxHeading";
            @__ctrl.Text = "Change Password";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_CurrentPassword() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_CurrentPassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_CurrentPassword";
            @__ctrl.Text = "Current Password";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxb_CurrentPassword() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txb_CurrentPassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txb_CurrentPassword";
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(125D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlrequire_CurrentPassword() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            this.require_CurrentPassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "require_CurrentPassword";
            @__ctrl.ValidationGroup = "ChangePassword";
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            @__ctrl.CssClass = "pxErrorText";
            @__ctrl.ControlToValidate = "txb_CurrentPassword";
            @__ctrl.ErrorMessage = "Password is required.";
            @__ctrl.Enabled = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_NewPassword() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_NewPassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_NewPassword";
            @__ctrl.Text = "New Password";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxb_NewPassword() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txb_NewPassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txb_NewPassword";
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(125D, global::System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.AutoPostBack = true;
            @__ctrl.TextChanged -= new System.EventHandler(this.ValidatePassword);
            @__ctrl.TextChanged += new System.EventHandler(this.ValidatePassword);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlrequire_NewPassword() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            this.require_NewPassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "require_NewPassword";
            @__ctrl.ValidationGroup = "ChangePassword";
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            @__ctrl.CssClass = "pxErrorText";
            @__ctrl.ControlToValidate = "txb_NewPassword";
            @__ctrl.ErrorMessage = "Password is required.";
            @__ctrl.Enabled = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.CustomValidator @__BuildControlcustom_Password() {
            global::System.Web.UI.WebControls.CustomValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.CustomValidator();
            this.custom_Password = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "custom_Password";
            @__ctrl.ValidationGroup = "ChangePassword";
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            @__ctrl.CssClass = "pxErrorText";
            @__ctrl.ErrorMessage = "Password does not <br /> meet requirements.";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_ConfirmNewPassword() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_ConfirmNewPassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_ConfirmNewPassword";
            @__ctrl.Text = "Confirm New Password";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxb_ConfirmNewPassword() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txb_ConfirmNewPassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txb_ConfirmNewPassword";
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(125D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.CompareValidator @__BuildControlcompare_ConfirmPassword() {
            global::System.Web.UI.WebControls.CompareValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.CompareValidator();
            this.compare_ConfirmPassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "compare_ConfirmPassword";
            @__ctrl.ValidationGroup = "ChangePassword";
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            @__ctrl.CssClass = "pxErrorText";
            @__ctrl.ControlToValidate = "txb_ConfirmNewPassword";
            @__ctrl.ControlToCompare = "txb_NewPassword";
            @__ctrl.ErrorMessage = "Passwords must match.";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtn_ChangePassword() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btn_ChangePassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btn_ChangePassword";
            @__ctrl.ValidationGroup = "ChangePassword";
            @__ctrl.CssClass = "pxBtn";
            @__ctrl.Text = "Change Password";
            @__ctrl.Click -= new System.EventHandler(this.ChangePassword_Click);
            @__ctrl.Click += new System.EventHandler(this.ChangePassword_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtn_CancelChangePassword() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btn_CancelChangePassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btn_CancelChangePassword";
            @__ctrl.CssClass = "pxBtnCancel";
            @__ctrl.Text = "Cancel";
            @__ctrl.CausesValidation = false;
            @__ctrl.Click -= new System.EventHandler(this.HideChangePassword);
            @__ctrl.Click += new System.EventHandler(this.HideChangePassword);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlsection_ChangePassword() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.section_ChangePassword = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "section_ChangePassword";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "pxChangeSetting");
            @__ctrl.Visible = false;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllbl_ChangePassword();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        <div class=\"clear\"></div>\r\n                        <div" +
                        " class=\"pxFields\">\r\n                            "));
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControllbl_CurrentPassword();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            @__ctrl3 = this.@__BuildControltxb_CurrentPassword();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl4;
            @__ctrl4 = this.@__BuildControlrequire_CurrentPassword();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("        \r\n                        </div>\r\n                        <div class=\"cle" +
                        "ar\"></div>\r\n                        <div class=\"pxFields\">\r\n                    " +
                        "        "));
            global::System.Web.UI.WebControls.Label @__ctrl5;
            @__ctrl5 = this.@__BuildControllbl_NewPassword();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            @__ctrl6 = this.@__BuildControltxb_NewPassword();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl7;
            @__ctrl7 = this.@__BuildControlrequire_NewPassword();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("        \r\n                            "));
            global::System.Web.UI.WebControls.CustomValidator @__ctrl8;
            @__ctrl8 = this.@__BuildControlcustom_Password();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </div>\r\n                        <div class=\"pxFields\">\r" +
                        "\n                            "));
            global::System.Web.UI.WebControls.Label @__ctrl9;
            @__ctrl9 = this.@__BuildControllbl_ConfirmNewPassword();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl10;
            @__ctrl10 = this.@__BuildControltxb_ConfirmNewPassword();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("                    \r\n                            "));
            global::System.Web.UI.WebControls.CompareValidator @__ctrl11;
            @__ctrl11 = this.@__BuildControlcompare_ConfirmPassword();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("   \r\n                        </div>\r\n                        <div class=\"clear\"><" +
                        "/div>\r\n                        <div class=\"pxButtons\">\r\n                        " +
                        "    "));
            global::System.Web.UI.WebControls.Button @__ctrl12;
            @__ctrl12 = this.@__BuildControlbtn_ChangePassword();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
            global::System.Web.UI.WebControls.Button @__ctrl13;
            @__ctrl13 = this.@__BuildControlbtn_CancelChangePassword();
            @__parser.AddParsedSubObject(@__ctrl13);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </div>\r\n                    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_DisplayPhoneNumber() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_DisplayPhoneNumber = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_DisplayPhoneNumber";
            @__ctrl.CssClass = "pxLabel";
            @__ctrl.Text = "Phone Number";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Literal @__BuildControlltr_DisplayPhoneNumber() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.ltr_DisplayPhoneNumber = @__ctrl;
            @__ctrl.ID = "ltr_DisplayPhoneNumber";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllnk_ChangePhoneNumber() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lnk_ChangePhoneNumber = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lnk_ChangePhoneNumber";
            @__ctrl.CausesValidation = false;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Change Phone Number"));
            @__ctrl.Click -= new System.EventHandler(this.ShowChangePhoneNumber);
            @__ctrl.Click += new System.EventHandler(this.ShowChangePhoneNumber);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlsection_DisplayPhoneNumber() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.section_DisplayPhoneNumber = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "section_DisplayPhoneNumber";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "pxDisplaySetting");
            @__ctrl.Visible = true;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllbl_DisplayPhoneNumber();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        <div class=\"clear\"></div>\r\n                        "));
            global::System.Web.UI.WebControls.Literal @__ctrl2;
            @__ctrl2 = this.@__BuildControlltr_DisplayPhoneNumber();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl3;
            @__ctrl3 = this.@__BuildControllnk_ChangePhoneNumber();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_ChangePhoneNumber() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_ChangePhoneNumber = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_ChangePhoneNumber";
            @__ctrl.CssClass = "pxHeading";
            @__ctrl.Text = "Change Phone Number";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_NewPhoneNumber() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_NewPhoneNumber = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_NewPhoneNumber";
            @__ctrl.Text = "New Phone Number";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxb_NewPhoneNumber() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txb_NewPhoneNumber = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txb_NewPhoneNumber";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(125D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlrequire_PhoneNumber() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            this.require_PhoneNumber = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "require_PhoneNumber";
            @__ctrl.ValidationGroup = "ChangePhoneNumber";
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            @__ctrl.CssClass = "pxErrorText";
            @__ctrl.ControlToValidate = "txb_NewPhoneNumber";
            @__ctrl.ErrorMessage = "Phone Number is required.";
            @__ctrl.Enabled = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.RegularExpressionValidator @__BuildControlregex_PhoneNumber() {
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RegularExpressionValidator();
            this.regex_PhoneNumber = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "regex_PhoneNumber";
            @__ctrl.ValidationGroup = "ChangePhoneNumber";
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            @__ctrl.CssClass = "pxErrorText";
            @__ctrl.ControlToValidate = "txb_NewPhoneNumber";
            @__ctrl.ValidationExpression = "^((\\(\\d{3}\\) ?)|(\\d{3}-))?\\d{3}-\\d{4}( (|x|ext|ext.)\\d{1,5})?$";
            @__ctrl.ErrorMessage = "Invalid phone number.";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtn_ChangePhoneNumber() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btn_ChangePhoneNumber = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btn_ChangePhoneNumber";
            @__ctrl.ValidationGroup = "ChangePhoneNumber";
            @__ctrl.CssClass = "pxBtn";
            @__ctrl.Text = "Change Phone Number";
            @__ctrl.Click -= new System.EventHandler(this.ChangePhoneNumber_Click);
            @__ctrl.Click += new System.EventHandler(this.ChangePhoneNumber_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtn_CancelChangePhoneNumber() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btn_CancelChangePhoneNumber = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btn_CancelChangePhoneNumber";
            @__ctrl.CssClass = "pxBtnCancel";
            @__ctrl.Text = "Cancel";
            @__ctrl.CausesValidation = false;
            @__ctrl.Click -= new System.EventHandler(this.HideChangePhoneNumber);
            @__ctrl.Click += new System.EventHandler(this.HideChangePhoneNumber);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlsection_ChangePhoneNumber() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.section_ChangePhoneNumber = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "section_ChangePhoneNumber";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "pxChangeSetting");
            @__ctrl.Visible = false;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllbl_ChangePhoneNumber();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        <div class=\"clear\"></div>\r\n                        <div" +
                        " class=\"pxFields\">\r\n                            "));
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControllbl_NewPhoneNumber();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            @__ctrl3 = this.@__BuildControltxb_NewPhoneNumber();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("                    \r\n                            "));
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl4;
            @__ctrl4 = this.@__BuildControlrequire_PhoneNumber();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl5;
            @__ctrl5 = this.@__BuildControlregex_PhoneNumber();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </div>\r\n                        <div class=\"clear\"></di" +
                        "v>\r\n                        <div class=\"pxButtons\">\r\n                           " +
                        " "));
            global::System.Web.UI.WebControls.Button @__ctrl6;
            @__ctrl6 = this.@__BuildControlbtn_ChangePhoneNumber();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
            global::System.Web.UI.WebControls.Button @__ctrl7;
            @__ctrl7 = this.@__BuildControlbtn_CancelChangePhoneNumber();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </div>\r\n                    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                <div class=\"pxWrapper\">\r\n                    "));
            global::System.Web.UI.WebControls.Literal @__ctrl1;
            @__ctrl1 = this.@__BuildControlltr_Debug();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                    <!-- Display Name -->\r\n                    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl2;
            @__ctrl2 = this.@__BuildControlsection_DisplayName();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                    <!-- Change Name -->\r\n                    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl3;
            @__ctrl3 = this.@__BuildControlsection_ChangeName();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                    <!-- Display Password -->\r\n                    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl4;
            @__ctrl4 = this.@__BuildControlsection_DisplayPassword();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                    <!-- Change Password -->\r\n                    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl5;
            @__ctrl5 = this.@__BuildControlsection_ChangePassword();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                    <!-- Display Phone Number -->\r\n                    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl6;
            @__ctrl6 = this.@__BuildControlsection_DisplayPhoneNumber();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                \r\n                    <!-- Change Phone Number -->\r\n           " +
                        "         "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl7;
            @__ctrl7 = this.@__BuildControlsection_ChangePhoneNumber();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                </div>\r\n                                \r\n\t        "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.UpdatePanel @__BuildControlUpdatePanelOne() {
            global::System.Web.UI.UpdatePanel @__ctrl;
            @__ctrl = new global::System.Web.UI.UpdatePanel();
            this.UpdatePanelOne = @__ctrl;
            @__ctrl.ContentTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control2));
            @__ctrl.ID = "UpdatePanelOne";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::Px.SelfService.WebParts.PersonalSettings.PersonalSettings @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<script type=\"text/javascript\">\r\n    \r\n    $(document).ready(function () {\r\n " +
                        "       new User();\r\n    });\r\n    \r\n    function Dialog(text) {\r\n        var html" +
                        " = \"<div class=\'modal fade\'><div class=\'modal-dialog\'><div class=\'modal-content\'" +
                        "><div class=\'modal-body\'><p>\" + text + \"</p></div><div class=\'modal-footer\'><but" +
                        "ton type=\'button\' class=\'btn btn-default\' data-dismiss=\'modal\'>Close</button></d" +
                        "iv></div></div></div>\";\r\n        $(html).modal();\r\n    }\r\n\r\n    function OnUpdat" +
                        "eValidators() {\r\n        for (var i = 0; i < Page_Validators.length; i++) {\r\n   " +
                        "         var validator = Page_Validators[i];\r\n            var control = document" +
                        ".getElementById(validator.controltovalidate);\r\n            if (control != null &" +
                        "& control.style != null) {\r\n                control.style.border = CheckValidato" +
                        "rsForControl(control) ? \"1px solid #ABABAB\" : \"2px solid #F3A94C\";\r\n            " +
                        "    //if (!val.isvalid) {\r\n                //ctrl.style.border = \"2px solid #F3A" +
                        "94C\";\r\n                //} else {\r\n                //ctrl.style.border = \"1px so" +
                        "lid #ABABAB\";\r\n                //}\r\n            }\r\n        }\r\n    }\r\n    \r\n    f" +
                        "unction CheckValidatorsForControl(control) {\r\n        for (var i = 0; i < contro" +
                        "l.Validators.length; i++) {\r\n            if (!control.Validators[i].isvalid) {\r\n" +
                        "                return false;\r\n            }\r\n        }\r\n        return true;\r\n " +
                        "   }\r\n    \r\n</script>\r\n\r\n<style>\r\n    div.welcome { padding-top: 0 !important; }" +
                        "\r\n    .welcome-content {margin-top:0 !important;}    \r\n\r\n    #PxBg { background-" +
                        "color: #E9E9E9 !important; }\r\n\r\n    .activeTab {  }\r\n    .inactiveTab { backgrou" +
                        "nd-color: #E9E9E9; margin-left: 20px; padding: 5px; float: left; border-left: 1p" +
                        "x solid #C1C1C1; border-top: 1px solid #C1C1C1; border-right: 1px solid #C1C1C1 " +
                        "}\r\n    .inactiveTab a { color: #454545; }\r\n    .inactiveTab a:hover { color: #45" +
                        "4545; }\r\n    .inactiveTab a:visited { color: #454545; }\r\n    .tabs ul {list-styl" +
                        "e: none; margin: 0px; padding: 0px; padding-left: 15px; background-color: #E9E9E" +
                        "9; }\r\n    .tabs li {border-width: 1px 1px 0px; border-style: solid; border-color" +
                        ": #CCCCCC; margin: 0px;  margin-right: 7px; border-top-left-radius: 3px; border-" +
                        "top-right-radius: 3px; float: left;}\r\n    .tabs a {background: #F3F3F3; height: " +
                        "25px;  padding: 5px 8px 0 8px; color: #454545; font: 12px Open Sans bold; text-d" +
                        "ecoration: none; display: block; margin-bottom: -1px}\r\n    .tabs a:hover { }\r\n\r\n" +
                        "    .tabs .activeTab {background-color: white; height: 26px; margin-bottom: -2px" +
                        "; position: relative;}\r\n    .tabs .activeTab a { }\r\n    #content {padding: 0px 1" +
                        "em; border-top: 1px solid #cccccc; clear: both;}\r\n\r\n    .pxWrapper { border-top:" +
                        " 1px solid #cccccc; border-bottom: 1px solid #cccccc; background-color: white; p" +
                        "adding-top: 24px; min-height: 269px; }\r\n    .pxDisplaySetting { background-color" +
                        ": #FFFFFF; padding-bottom:8px; padding-left: 16px; }\r\n    .pxDisplaySetting a, ." +
                        "pxDisplaySetting a:visited { color: #2B5272; text-decoration: underline; }\r\n    " +
                        ".pxChangeSetting { background-color: #F3F3F3; padding: 13px 0 16px 16px; border-" +
                        "top: 1px solid #cccccc; border-bottom: 1px solid #cccccc; }\r\n    .pxHeading { co" +
                        "lor: #454545; font-family:Open Sans Bold; font-size: 11px; text-transform: upper" +
                        "case; }\r\n    .pxLabel { font-weight: bold; }\r\n    .pxButtons { margin-top: 10px;" +
                        " }\r\n    .pxErrorText { color:#F3A94C }    \r\n    .pxErrorTextBox {border-width: 2" +
                        "px; border-color: #F3A94C }    \r\n    .clear { clear: both; }\r\n</style>\r\n\r\n    <!" +
                        "-- Shared Navigation -->\r\n    "));
            global::System.Web.UI.WebControls.Literal @__ctrl1;
            @__ctrl1 = this.@__BuildControlltr_SharedNav();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            global::System.Web.UI.WebControls.Literal @__ctrl2;
            @__ctrl2 = this.@__BuildControlltr_Username();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

    <!-- Title -->
    <div style=""margin-left: 20px; margin-top: 10px; margin-bottom: 10px;"">
        <span class=""pxSettingsTitle"">Supplier Oasis Settings</span>
    </div>

    <!-- Tabs -->
    <div class=""tabs"">
        <ul>
            <li><a href=""/pages/CompanySettings.aspx"" >Company Settings</a></li>
            <li><a href=""#"" class=""activeTab"">Personal Settings</a></li>
            <li><a href=""/pages/WarehouseSettings.aspx"">Warehouse Settings</a></li>
        </ul>
    </div>
        <div class=""clear""></div>

    <!-- Form -->
    <div>
        
        <div style=""display: none;"">
            "));
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl3;
            @__ctrl3 = this.@__BuildControldummyValidator();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            @__ctrl4 = this.@__BuildControldummyTextBox();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("            \r\n        </div>       \r\n        \r\n        "));
            global::System.Web.UI.UpdatePanel @__ctrl5;
            @__ctrl5 = this.@__BuildControlUpdatePanelOne();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                \r\n    </div>\r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
