//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Px.SelfService.WebParts.EditWarehouse {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class EditWarehouse {
        
        protected global::System.Web.UI.HtmlControls.HtmlInputButton btnSave;
        
        protected global::System.Web.UI.HtmlControls.HtmlInputButton btnCancel;
        
        public static implicit operator global::System.Web.UI.TemplateControl(EditWarehouse target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlInputButton @__BuildControlbtnSave() {
            global::System.Web.UI.HtmlControls.HtmlInputButton @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputButton();
            this.btnSave = @__ctrl;
            @__ctrl.ID = "btnSave";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "button");
            @__ctrl.Value = "Save";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "settingsButton");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlInputButton @__BuildControlbtnCancel() {
            global::System.Web.UI.HtmlControls.HtmlInputButton @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputButton();
            this.btnCancel = @__ctrl;
            @__ctrl.ID = "btnCancel";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "button");
            @__ctrl.Value = "Cancel";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "settingsButton");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::Px.SelfService.WebParts.EditWarehouse.EditWarehouse @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n<!-- LAYOUT -->\r\n<link href=\"/_layouts/15/Px.SelfService/CSS/pxSettings.css" +
                        "\" rel=\"stylesheet\" type=\"text/css\" />\r\n\r\n<!-- CONTENT -->\r\n<div class=\"pxWrap\">\r" +
                        "\n    <span class=\"sectionHeading\">Edit...</span>\r\n    "));
            global::System.Web.UI.HtmlControls.HtmlInputButton @__ctrl1;
            @__ctrl1 = this.@__BuildControlbtnSave();
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.HtmlControls.HtmlInputButton @__ctrl2;
            @__ctrl2 = this.@__BuildControlbtnCancel();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n</div>\r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
