//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Px.SelfService.WebParts.RecoverPassword {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class RecoverPassword {
        
        protected global::System.Web.UI.WebControls.Literal ltr_Notification;
        
        protected global::System.Web.UI.WebControls.Panel pnl_Notifications;
        
        protected global::System.Web.UI.WebControls.Label lbl_Instruction;
        
        protected global::System.Web.UI.WebControls.Label lbl_Prompt;
        
        protected global::System.Web.UI.WebControls.TextBox txb_Prompt;
        
        protected global::System.Web.UI.WebControls.Label lbl_Confirm;
        
        protected global::System.Web.UI.WebControls.TextBox txb_Confirm;
        
        protected global::System.Web.UI.WebControls.Button btn_Change;
        
        protected global::System.Web.UI.WebControls.Button btn_Cancel;
        
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator;
        
        protected global::System.Web.UI.WebControls.RegularExpressionValidator regex_NewPassword;
        
        protected global::System.Web.UI.WebControls.CompareValidator CompareValidator;
        
        public static implicit operator global::System.Web.UI.TemplateControl(RecoverPassword target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Literal @__BuildControlltr_Notification() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.ltr_Notification = @__ctrl;
            @__ctrl.ID = "ltr_Notification";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnl_Notifications() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            this.pnl_Notifications = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "pnl_Notifications";
            @__ctrl.Visible = false;
            @__ctrl.CssClass = "alerts";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            global::System.Web.UI.WebControls.Literal @__ctrl1;
            @__ctrl1 = this.@__BuildControlltr_Notification();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_Instruction() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_Instruction = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_Instruction";
            @__ctrl.Text = "Please create your new password:";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_Prompt() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_Prompt = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_Prompt";
            @__ctrl.Text = "New Password";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxb_Prompt() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txb_Prompt = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txb_Prompt";
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(147D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_Confirm() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_Confirm = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_Confirm";
            @__ctrl.Text = "Confirm New Password";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxb_Confirm() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txb_Confirm = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txb_Confirm";
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(147D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtn_Change() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btn_Change = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btn_Change";
            @__ctrl.Text = "Change Password";
            @__ctrl.Enabled = true;
            @__ctrl.CssClass = "pxBtn";
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(28D, global::System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.Click -= new System.EventHandler(this.btn_Change_Click);
            @__ctrl.Click += new System.EventHandler(this.btn_Change_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtn_Cancel() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btn_Cancel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btn_Cancel";
            @__ctrl.Text = "Cancel";
            @__ctrl.CssClass = "pxBtnCancel";
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(28D, global::System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.Click -= new System.EventHandler(this.btn_Cancel_Click);
            @__ctrl.Click += new System.EventHandler(this.btn_Cancel_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            this.RequiredFieldValidator = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "RequiredFieldValidator";
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            @__ctrl.CssClass = "text-error";
            @__ctrl.ControlToValidate = "txb_Prompt";
            @__ctrl.ErrorMessage = "Password is required.";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.RegularExpressionValidator @__BuildControlregex_NewPassword() {
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RegularExpressionValidator();
            this.regex_NewPassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "regex_NewPassword";
            @__ctrl.ValidationGroup = "ChangePassword";
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            @__ctrl.CssClass = "pxErrorText";
            @__ctrl.ControlToValidate = "txb_Prompt";
            @__ctrl.ValidationExpression = "((?=.*\\d)(?=.*[A-z])(?=.*[!\"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~]).{8,32})";
            @__ctrl.ErrorMessage = "Password does not <br /> meet requirements.";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.CompareValidator @__BuildControlCompareValidator() {
            global::System.Web.UI.WebControls.CompareValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.CompareValidator();
            this.CompareValidator = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "CompareValidator";
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            @__ctrl.CssClass = "text-error";
            @__ctrl.ControlToValidate = "txb_Prompt";
            @__ctrl.ControlToCompare = "txb_Confirm";
            @__ctrl.ErrorMessage = "Passwords do not match.";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::Px.SelfService.WebParts.RecoverPassword.RecoverPassword @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    <style type=\"text/css\">\r\n        #s4-workspace { border-radius: 3px; widt" +
                        "h:405px !important; height: auto !important; position:absolute; left:50%; top:50" +
                        "%; margin-left: -225px !important; margin-top: -100px !important; }\r\n        #s4" +
                        "-bodyContainer { padding-bottom: 0 !important; }\r\n        #AnonymousHeader { bac" +
                        "kground: #FFFFFF; margin: -15px 0 0 0; padding: 7px; }\r\n        a, input[type=\'t" +
                        "ext\'], input[type=\'password\'] { display:block; padding-right: 10px; margin-top: " +
                        "2px; }\r\n        label { display:inline }\r\n        .terms-input { padding: 4px 6p" +
                        "x; border-radius: 4px; height: 20px; color: rgb(85, 85, 85); line-height: 20px; " +
                        "font-size: 14px; vertical-align: middle; display: inline-block; -webkit-border-r" +
                        "adius: 4px; -moz-border-radius: 4px; }\r\n        .terms-input { border: 1px solid" +
                        " rgb(204, 204, 204); transition:border 0.2s linear, box-shadow 0.2s linear; box-" +
                        "shadow: inset 0px 1px 1px rgba(0,0,0,0.075); background-color: rgb(255, 255, 255" +
                        "); -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075); -moz-box-shadow: in" +
                        "set 0 1px 1px rgba(0, 0, 0, 0.075); -webkit-transition: border linear .2s, box-s" +
                        "hadow linear .2s; -moz-transition: border linear .2s, box-shadow linear .2s; -o-" +
                        "transition: border linear .2s, box-shadow linear .2s; }\r\n        .terms-input { " +
                        "overflow: hidden; overflow-y: scroll; width: 810px; height: 164px; }\r\n        .t" +
                        "erms-input:focus { border-color: rgba(82, 168, 236, 0.8); outline: dotted thin; " +
                        "box-shadow: inset 0px 1px 1px rgba(0,0,0,0.075), 0px 0px 8px rgba(82,168,236,0.6" +
                        "); -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(82, 16" +
                        "8, 236, 0.6); -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgb" +
                        "a(82, 168, 236, 0.6); }\r\n        .alerts { background: #EF2710; color: white; he" +
                        "ight: 30px; line-height: 30px; text-align: center; }                \r\n        .p" +
                        "xContent { padding: 10px 10px 0 10px; }\r\n        input[type=\'password\'] { paddin" +
                        "g-right: 3px; }\r\n        div.article, div.welcome { padding-bottom: 0px !importa" +
                        "nt; }\r\n        .ms-table .ms-fullWidth { display:none; }\r\n    </style>\r\n\r\n    <d" +
                        "iv id=\"AnonymousHeader\">\r\n        <div><img class=\"logo\" src=\"/_layouts/15/Px.Br" +
                        "anding/Images/Logo-195x50.png\" alt=\"\"></div>\r\n        <div style=\"clear:both\"></" +
                        "div>\r\n    </div>\r\n\r\n    <div>\r\n        "));
            global::System.Web.UI.WebControls.Panel @__ctrl1;
            @__ctrl1 = this.@__BuildControlpnl_Notifications();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n\r\n    <div class=\"pxContent\">\r\n    \r\n        <div>"));
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControllbl_Instruction();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</div>\r\n    \r\n        <div style=\"margin-top: 5px; float: left\">\r\n            <di" +
                        "v class=\"pxFields\" >\r\n                <div>"));
            global::System.Web.UI.WebControls.Label @__ctrl3;
            @__ctrl3 = this.@__BuildControllbl_Prompt();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</div>\r\n                <div>"));
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            @__ctrl4 = this.@__BuildControltxb_Prompt();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</div>\r\n            </div>\r\n            <div class=\"clear\"></div>\r\n            <d" +
                        "iv class=\"pxFields\" >\r\n                <div>"));
            global::System.Web.UI.WebControls.Label @__ctrl5;
            @__ctrl5 = this.@__BuildControllbl_Confirm();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</div>\r\n                <div>"));
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            @__ctrl6 = this.@__BuildControltxb_Confirm();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"</div>
            </div>
            <div class=""clear"" style=""height: 10px;""></div>
        </div>
    
        <div style=""color:#454545; font:12px 'Open Sans'; line-height:1; width: 215px; margin-left: 3px; margin-top: 30px; float: left"">
            NOTE: Password must be at least eight characters long and contain at least one alpha character [a-z], 
            one numeric character [0-9], and one special character [` ! @ $ % ^ & * ( ) - _ = + [ ] ; : ‘ “ , < . > / ?]
        </div>
        <div class=""clear""></div>

        <div>
            "));
            global::System.Web.UI.WebControls.Button @__ctrl7;
            @__ctrl7 = this.@__BuildControlbtn_Change();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            global::System.Web.UI.WebControls.Button @__ctrl8;
            @__ctrl8 = this.@__BuildControlbtn_Cancel();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        </div>\r\n        \r\n        <div>\r\n            "));
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl9;
            @__ctrl9 = this.@__BuildControlRequiredFieldValidator();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl10;
            @__ctrl10 = this.@__BuildControlregex_NewPassword();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            global::System.Web.UI.WebControls.CompareValidator @__ctrl11;
            @__ctrl11 = this.@__BuildControlCompareValidator();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        </div>\r\n    \r\n    </div>\r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
